language: python

python:
  - "3.6"
  # - "3.7"
  # - "3.8"
  # - "3.9"

before_install:
  - sudo apt-get install -y ffmpeg

install:
  # - pip install coveralls
  - pip install .

script:
  - tests/testing.py
  # - coverage run tests/testing.py