language: python

python:
  - "3.8"
  # - "3.9"

before_install:
  - sudo apt-get install -y ffmpeg

install:
  # - pip install coveralls
  # make clipboard work on linux
  - pip install gtk
  - pip install .

before_script:
  - chmod +x tests/testing.py

script:
  - python tests/testing.py
  # - coverage run tests/testing.py