language: python

python:
  - "3.8"
  # - "3.9"

before_install:
  - sudo apt-get install -y ffmpeg
  - sudo apt-get install xsel   # to make clipboard work on linux

install:
  # - pip install coveralls
  - pip install .

before_script:
  - chmod +x tests/testing.py

script:
  - python tests/testing.py
  # - coverage run tests/testing.py